export type LPICVideoSeed = {
  index: number;
  title: string;
  url: string;
  durationSeconds: number;
  topic: string;
};

// Verified from the playlist checklist generated by the playlist-study skill.
export const LPIC_VIDEO_DATA: LPICVideoSeed[] = [
  {
    "index": 1,
    "title": "الپیک ۱ - ۰۰۱ -  مقدمه و شروع",
    "url": "https://www.youtube.com/watch?v=cqfrsmg4BKo&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=1&pp=iAQB",
    "durationSeconds": 441,
    "topic": "Introduction and lab setup"
  },
  {
    "index": 2,
    "title": "الپیک ۱ - ۰۰۲ -  درست کردن لب - نصب فدورا",
    "url": "https://www.youtube.com/watch?v=hBkCjrf1XZU&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=2&pp=iAQB",
    "durationSeconds": 725,
    "topic": "Introduction and lab setup"
  },
  {
    "index": 3,
    "title": "الپیک ۱ - ۰۰۳ -  ساخت یک آزمایشگاه - نصب اوبونتو",
    "url": "https://www.youtube.com/watch?v=Fi6cuzsTccM&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=3&pp=iAQB",
    "durationSeconds": 573,
    "topic": "Introduction and lab setup"
  },
  {
    "index": 4,
    "title": "الپیک ۱  - ۰۰۴ - ۱۰۱.۱ - قسمت ۱/۳ - شناخت و کار با سخت افزارها - درک سخت افزارها",
    "url": "https://www.youtube.com/watch?v=IX2Pe8KonE0&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=4&pp=iAQB",
    "durationSeconds": 903,
    "topic": "System architecture"
  },
  {
    "index": 5,
    "title": "الپیک  ۱ - ۰۰۵ - بخش ۱۰۱.۱ -  قسمت ۲/۳ - شناخت و کار با سخت افزارها - مفاهیم",
    "url": "https://www.youtube.com/watch?v=n4Xbl8mWIKo&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=5&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 1107,
    "topic": "System architecture"
  },
  {
    "index": 6,
    "title": "الپیک  ۱ - ۰۰۶ - بخش ۱۰۱.۱ -  قسمت ۳/۳ - شناخت و کار با سخت افزارها - دستورات مرتبط",
    "url": "https://www.youtube.com/watch?v=TfW4AyISd9A&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=6&pp=iAQB",
    "durationSeconds": 774,
    "topic": "System architecture"
  },
  {
    "index": 7,
    "title": "الپیک  ۱ - ۰۰۷ - بخش ۱۰۱.۲ -  قسمت ۱/۲ - روند بوت شدن سیستم ؛ درک مفاهیم و روند بوت",
    "url": "https://www.youtube.com/watch?v=zTv_HLfCtI8&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=7&pp=iAQB",
    "durationSeconds": 900,
    "topic": "System architecture"
  },
  {
    "index": 8,
    "title": "الپیک  ۱ - ۰۰۸ - بخش ۱۰۱.۲ - قسمت ۲/۲ - روند بوت شدن سیستم؛ سیستم‌دی، سیستم۵، ژورنال و لاگ‌ها",
    "url": "https://www.youtube.com/watch?v=qdS_nT-iRJQ&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=8&pp=iAQB",
    "durationSeconds": 1972,
    "topic": "System architecture"
  },
  {
    "index": 9,
    "title": "الپیک  ۱ - ۰۰۹ - بخش ۱۰۱.۳ - قسمت ۱/۲ - ران لول‌ها و تارگت ها - مفاهیم و تغییر",
    "url": "https://www.youtube.com/watch?v=TsMDqSRHCsQ&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=9&pp=iAQB",
    "durationSeconds": 1360,
    "topic": "System architecture"
  },
  {
    "index": 10,
    "title": "الپیک ۱ - ۰۱۰ - بخش ۱۰۱.۳ - قسمت ۲/۲ - ران لول‌ها و تارگت ‌ها، شات داون کردن سیستم  اطلاع به کاربران",
    "url": "https://www.youtube.com/watch?v=EU7f2gejq9g&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=10&pp=iAQB",
    "durationSeconds": 986,
    "topic": "System architecture"
  },
  {
    "index": 11,
    "title": "الپیک  ۱ - ۰۱۱ - ۱۰۲.۱ - ۱/۲ - طراحی ترکیب هارددیسک - استاندارد سلسله‌مراتبی فایل‌سیستم FHS",
    "url": "https://www.youtube.com/watch?v=eVrkF3fJ7LM&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=11&pp=iAQB",
    "durationSeconds": 1434,
    "topic": "Linux installation and package management"
  },
  {
    "index": 12,
    "title": "الپیک ۱ - ۰۱۲ - بخش ۱۰۲.۱ - ۲/۲ - طراحی ترکیب هارد دیسک - پارتیشن‌ها",
    "url": "https://www.youtube.com/watch?v=LdCMHzBIJYY&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=12&pp=iAQB",
    "durationSeconds": 1432,
    "topic": "Linux installation and package management"
  },
  {
    "index": 13,
    "title": "الپیک ۱ - ۰۱۳ - ماجول ۱۰۲.۱ - بخش جایزه - انواع سوئپ شامل پارتیشن، فایل و زد رم zram",
    "url": "https://www.youtube.com/watch?v=fp-cjNMQzx8&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=13&pp=iAQB",
    "durationSeconds": 989,
    "topic": "Linux installation and package management"
  },
  {
    "index": 14,
    "title": "الپیک ۱ -  ۰۱۴ - ماجول ۱۰۲.۲ - نصب و استفاده از بوت از بوت لودرها - قسمت یک از دو: گراب لگاسی",
    "url": "https://www.youtube.com/watch?v=5ccUQhN8hb0&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=14&pp=iAQB",
    "durationSeconds": 1178,
    "topic": "Linux installation and package management"
  },
  {
    "index": 15,
    "title": "الپیک ۱ - ۰۱۵ -  ماجول ۱۰۲.۲ - نصب و استفاده از بوت از بوت لودرها - قسمت دو از دو: گراب لگاسی",
    "url": "https://www.youtube.com/watch?v=_RZBUaXh4Dc&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=15&pp=iAQB",
    "durationSeconds": 1805,
    "topic": "Linux installation and package management"
  },
  {
    "index": 16,
    "title": "الپیک ۱ -  ۰۱۶ - ماجول ۱۰۲.۳ - مدیریت کتابخانه‌های اشتراکی Manage Shared Libraries",
    "url": "https://www.youtube.com/watch?v=pQdKWB375os&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=16&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 1523,
    "topic": "Linux installation and package management"
  },
  {
    "index": 17,
    "title": "الپیک ۱ - ۰۱۷ - کار با مدیر بسته های دبیانی - قسمت ۱/۲ - درک مفهوم منابع نرم افزاری / رپوزیتوری",
    "url": "https://www.youtube.com/watch?v=6Hu4EtLuHo0&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=17&pp=iAQB",
    "durationSeconds": 956,
    "topic": "Linux installation and package management"
  },
  {
    "index": 18,
    "title": "الپیک ۱ - ۰۱۸ - قسمت ۲/۲ -  نصب، حذف و بازتنظیم نرم افزارها در دبیان و مدیریت مستقل بسته‌ها",
    "url": "https://www.youtube.com/watch?v=U9tXLZou0LE&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=18&pp=iAQB",
    "durationSeconds": 1312,
    "topic": "Linux installation and package management"
  },
  {
    "index": 19,
    "title": "الپیک ۱ - ۰۱۹ - ماجول ۱۰۲.۵ - ۱/۲ - مدیریت بسته‌های لینوکس‌های مبتنی بر آر پی ام، بررسی Yum و Zypper",
    "url": "https://www.youtube.com/watch?v=-QmjrkTjM8U&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=19&pp=iAQB",
    "durationSeconds": 1230,
    "topic": "Linux installation and package management"
  },
  {
    "index": 20,
    "title": "الپیک ۱ - ۰۲۰ - ماجول ۱۰۲.۵ - ۲/۲ - مدیریت بسته‌های آر پی ام با دستور آر پی ام",
    "url": "https://www.youtube.com/watch?v=ePsJHPq9T2I&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=20&pp=iAQB",
    "durationSeconds": 1202,
    "topic": "Linux installation and package management"
  },
  {
    "index": 21,
    "title": "الپیک ۱ - ماجول ۱۰۲.۶ - لینوکس به عنوان  مهمان مجازی سازی",
    "url": "https://www.youtube.com/watch?v=yzecjNfqb70&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=21&pp=iAQB",
    "durationSeconds": 1370,
    "topic": "Linux installation and package management"
  },
  {
    "index": 22,
    "title": "کار کردن در خط فرمان - درک مفهوم شل (پوسته) و بش و دستورات مقدماتی",
    "url": "https://www.youtube.com/watch?v=MGgu5-XGk98&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=22&pp=iAQB",
    "durationSeconds": 1271,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 23,
    "title": "کار در خط فرمان - درک متغیرهای محیطی پوسته و استفاده از تاریخچه",
    "url": "https://www.youtube.com/watch?v=-fY1eIcxuxE&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=23&pp=iAQB",
    "durationSeconds": 1102,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 24,
    "title": "الپیک ۱ - ۰۲۴ - بخش ۱۰۳.۲ - فیلتر استریم‌های متنی با دستورات گنو - قسمت ۱/۴  - مشاهده فایل‌ها",
    "url": "https://www.youtube.com/watch?v=gQvJGwth71Y&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=24&pp=iAQB",
    "durationSeconds": 944,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 25,
    "title": "الپیک ۱ - ۰۲۵ - بخش ۱۰۳.۲ - فیلتر استریم‌های متنی با دستورات گنو - قسمت ۲/۴  - انتخاب بخش‌ها",
    "url": "https://www.youtube.com/watch?v=jRQUtijKl3A&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=25&pp=iAQB",
    "durationSeconds": 632,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 26,
    "title": "الپیک ۱ - ۰۲۶ - بخش ۱۰۳.۲ - فیلتر استریم‌های متنی با دستورات گنو - قسمت ۳/۴  - تغییر در استریم",
    "url": "https://www.youtube.com/watch?v=BoICAQWodbs&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=26&pp=iAQB",
    "durationSeconds": 846,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 27,
    "title": "الپیک ۱ - ۰۲۷ - بخش ۱۰۳.۲ - فیلتر استریم‌های متنی با دستورات گنو - قسمت ۴/۴  - آمار و دیتا و هش ها",
    "url": "https://www.youtube.com/watch?v=RyLLscJqvpc&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=27&pp=iAQB",
    "durationSeconds": 582,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 28,
    "title": "الپیک ۱ - ۰۲۸ - ماجول ۱۰۳.۳ - مدیریت فایل‌ها - بخش ۱/۳ - کپی، حذف، انتقال، ساخت و حذف دایرکتوری",
    "url": "https://www.youtube.com/watch?v=BDLETx3YtI4&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=28&pp=iAQB",
    "durationSeconds": 1291,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 29,
    "title": "الپیک ۱ - ۰۲۹ - ماجول ۱۰۳.۳ - مدیریت فایل‌ها - بخش ۲/۳ - دستورهای touch, dd, file و find",
    "url": "https://www.youtube.com/watch?v=r70id-wn01c&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=29&pp=iAQB",
    "durationSeconds": 1273,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 30,
    "title": "الپیک ۱ - ۰۳۰ - ماجول ۱۰۳.۳ - بخش ۳/۳ - مدیریت فایل ها، فشرده سازی و آرشیو کردن فایل ها",
    "url": "https://www.youtube.com/watch?v=NhfqHhUONt8&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=30&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 777,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 31,
    "title": "الپیک ۱ - ۰۳۱ - ۱۰۳.۴ - ۱/۲ - استفاده از استریم ها و ریدایرکت اونها در پوسته های یونیکسی",
    "url": "https://www.youtube.com/watch?v=tkSCVzXgVr4&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=31&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 846,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 32,
    "title": "الپیک ۱ - ۰۳۲ - ماجول ۱۰۳.۴ - بخش ۲/۲ - پایپ ها و دستورات xargs و tee",
    "url": "https://www.youtube.com/watch?v=rFDzzdPE8hA&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=32&pp=iAQB",
    "durationSeconds": 751,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 33,
    "title": "الپیک ۱ - ۰۳۳ - ماجول ۱۰۳.۵ - قسمت ۱/۳ - مدیریت پروسه‌ها در لینوکس",
    "url": "https://www.youtube.com/watch?v=PUc24E2PTa8&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=33&pp=iAQB",
    "durationSeconds": 1669,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 34,
    "title": "الپیک ۱ - ۰۳۴ - ماجول ۱۰۳.۵ - قسمت ۲/۳ - مانیتورینگ پروسه‌ها در لینوکس",
    "url": "https://www.youtube.com/watch?v=r81i4UgGf5E&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=34&pp=iAQB",
    "durationSeconds": 1053,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 35,
    "title": "الپیک ۱ - ۰۳۵ - ماجول ۱۰۳.۵ - قسمت ۳/۳ - مالتی پلکسرهای ترمینال مانند اسکرین و تی‌ماکس",
    "url": "https://www.youtube.com/watch?v=46qeODpfrH4&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=35&pp=iAQB",
    "durationSeconds": 624,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 36,
    "title": "الپیک ۱ - ۰۳۶ - ماجول ۱۰۳.۶ - بررسی و مدیریت الویت پروسس‌ها در لینوکس",
    "url": "https://www.youtube.com/watch?v=2iyH0UY3Lbg&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=36&pp=iAQB",
    "durationSeconds": 1044,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 37,
    "title": "الپیک ۱ - ۰۳۷ - ماجول ۱۰۳.۷ - رجکس ها و جستجو در فایل ها به کمک دستور گرپ",
    "url": "https://www.youtube.com/watch?v=0mPPJdJLxSM&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=37&pp=iAQB",
    "durationSeconds": 1587,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 38,
    "title": "الپیک ۱ - ۰۳۸ - ماجول ۱۰۳.۸ - استفاده از ادیتور vim و آشنایی با بقیه ادیتورهای لینوکسی",
    "url": "https://www.youtube.com/watch?v=ptzqP8aP9IQ&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=38&pp=iAQB",
    "durationSeconds": 1301,
    "topic": "GNU and Unix commands"
  },
  {
    "index": 39,
    "title": "الپیک ۱ - ۰۳۹ - ماجول ۱۰۴.۱ (۱/۲) - پارتیشن بندی با اف.دیسک، جی.دیسک و پارتد",
    "url": "https://www.youtube.com/watch?v=A-lLkxY-E4Y&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=39&pp=iAQB",
    "durationSeconds": 1349,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 40,
    "title": "الپیک ۱ - ۰۴۰ - ماجول ۱۰۴.۱ (۲/۲) - پارتیشن بندی با اف.دیسک، جی.دیسک و پارتد",
    "url": "https://www.youtube.com/watch?v=p8_e4eD-NO0&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=40&pp=iAQB",
    "durationSeconds": 1158,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 41,
    "title": "الپیک ۱ - ۰۴۱ - ماجول ۱۰۴.۲ - ۱/۲ - حفظ سلامت فایل سیستم، بررسی فضای خالی و میزان مصرف دیسک",
    "url": "https://www.youtube.com/watch?v=XrBZtkvtnzM&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=41&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 572,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 42,
    "title": "LPIC-1 - 042 - Module 104.2 - 2/2 - Maintaining File System Health, Checking and Repairing File S...",
    "url": "https://www.youtube.com/watch?v=LnIszyn0l7g&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=42&pp=iAQB",
    "durationSeconds": 749,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 43,
    "title": "الپیک ۱ - ۰۴۳ - ماجول ۱۰۴.۳ - ۱/۲ - ماونت و آن ماونت کردن فایل سیستم ها در دنیای لینوکس / یونیکس",
    "url": "https://www.youtube.com/watch?v=HahSq4lYS3I&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=43&pp=iAQB",
    "durationSeconds": 782,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 44,
    "title": "الپیک ۱ - ۰۴۴ - الپیک ۱ - ۰۴۴ - ماجول ۱۰۴.۳ - ۲/۲ - ماونت کردن با استفاده از  UUID و fstab",
    "url": "https://www.youtube.com/watch?v=x5zFaUVajJ4&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=44&pp=iAQB",
    "durationSeconds": 658,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 45,
    "title": "الپیک ۱ - ۰۴۵ - ماجول ۱۰۴.۴ - این از امتحان حذف شده پس موزیک خوب می‌ذاریم و باهاش همراه می‌شیم (:",
    "url": "https://www.youtube.com/watch?v=DPZ_m862xz4&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=45&pp=iAQB",
    "durationSeconds": 66,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 46,
    "title": "الپیک ۱ - ۰۴۶ - ماجول ۱۰۴.۵ - ۱/۲ - یوزر و گروه و دسترسی‌ها در دنیای لینوکس",
    "url": "https://www.youtube.com/watch?v=CEW_ozeLeK0&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=46&pp=iAQB",
    "durationSeconds": 753,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 47,
    "title": "الپیک ۱ - ۰۴۷ - ماجول ۱۰۴.۵ - ۲/۲ - تنظیم دسترسی و مالکیت فایل ها و بیت‌های اکسس و یو.ماسک",
    "url": "https://www.youtube.com/watch?v=q9UZ4LhfLvI&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=47&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 1099,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 48,
    "title": "الپیک ۱ - ۰۴۸ - ماجول ۱۰۴.۶ - هارد و سافت لینک‌ها در لینوکس؛ مفهوم، استفاده و کاربرد",
    "url": "https://www.youtube.com/watch?v=35vB01RcqgM&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=48&pp=iAQB",
    "durationSeconds": 702,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 49,
    "title": "الپیک ۱ - ۰۴۹ - ماجول ۱۰۴.۷ - ساختار سلسله مراتبی فایل‌سیستم یونیکس و لینوکس و پیدا کردن جای فایل ها",
    "url": "https://www.youtube.com/watch?v=hO6qK-i3cXc&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=49&pp=iAQB",
    "durationSeconds": 822,
    "topic": "Devices, Linux filesystems, and FHS"
  },
  {
    "index": 50,
    "title": "الپیک ۱ - ۰۵۰ - ۱۰۵.۱ - بخش ۱/۲ - متغیرهای محیطی شل",
    "url": "https://www.youtube.com/watch?v=toNYKaYgaTM&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=50&pp=iAQB",
    "durationSeconds": 1449,
    "topic": "Shells and shell scripting"
  },
  {
    "index": 51,
    "title": "الپیک ۱ - ۰۵۱ - - ۱۰۵.۱ - بخش ۲/۲ - حالت‌های مختلف شل، شامل لاگین شل، تعاملی و غیرتعاملی",
    "url": "https://www.youtube.com/watch?v=MLzH5o9-iRc&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=51&pp=iAQB",
    "durationSeconds": 708,
    "topic": "Shells and shell scripting"
  },
  {
    "index": 52,
    "title": "الپیک ۱ - ۰۵۲ - ۱۰۵.۲ - بخش ۱/۲ - مقدمات شل اسکریپت نویسی شامل شبنگ، متغیرهای شل اسکریپت و اجرا",
    "url": "https://www.youtube.com/watch?v=VeFp-nxQ2Io&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=52&pp=iAQB",
    "durationSeconds": 1140,
    "topic": "Shells and shell scripting"
  },
  {
    "index": 53,
    "title": "الپیک ۱ - ۰۵۳ - ۱۰۵.۲ - بخش ۲/۲ - مقدمات شل اسکریپت نویسی، شرط‌ها و حلقه‌ها و خروجی برنامه‌ها",
    "url": "https://www.youtube.com/watch?v=KcNgHdslQCM&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=53&pp=iAQB",
    "durationSeconds": 1302,
    "topic": "Shells and shell scripting"
  },
  {
    "index": 54,
    "title": "الپیک ۱ - ۰۵۴ - ۱۰۶.۱ - درک لایه گرافیکی در لینوکس و نصب و تنظیمات ایکس ۱۱",
    "url": "https://www.youtube.com/watch?v=JqiT4rsTvUo&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=54&pp=iAQB",
    "durationSeconds": 1329,
    "topic": "User interfaces and desktops"
  },
  {
    "index": 55,
    "title": "الپیک ۱ - ۰۵۵ - محیط‌های گرافیکی در لینوکس (کی دی ای، گنوم و ایکس اف سی ای) و شیوه اتصال راه دور",
    "url": "https://www.youtube.com/watch?v=MSmc0sJ9KV0&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=55&pp=iAQB",
    "durationSeconds": 822,
    "topic": "User interfaces and desktops"
  },
  {
    "index": 56,
    "title": "الپیک ۱ - ۰۵۶ - دسترسی‌پذیری در دنیای گنو/لینوکس",
    "url": "https://www.youtube.com/watch?v=LoqbSL89PUc&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=56&pp=iAQB",
    "durationSeconds": 458,
    "topic": "User interfaces and desktops"
  },
  {
    "index": 57,
    "title": "الپیک ۱ - ۰۵۷ - ماجول ۱۰۷.۱ - ۱/۲ - مدیریت کاربران و گروه‌ها؛ حذف و تغییر و اضافه و تغییر پسورد",
    "url": "https://www.youtube.com/watch?v=wopNdXmXKj0&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=57&pp=iAQB",
    "durationSeconds": 566,
    "topic": "Administrative tasks"
  },
  {
    "index": 58,
    "title": "الپیک ۱ - ۰۵۸ - ماجول ۱۰۷.۱ - ۲/۲ - مدیریت کاربران و گروه‌ها؛ فایل‌های مرتبط با این اطلاعات",
    "url": "https://www.youtube.com/watch?v=jRkA48_-vCw&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=58&pp=iAQB",
    "durationSeconds": 648,
    "topic": "Administrative tasks"
  },
  {
    "index": 59,
    "title": "الپیک ۱ - ۰۵۹ - ماجول ۱۰۷.۲ - برنامه‌ریزی و زمان بندی کارها از طریق کرون، ات و تایمرهای سیستم‌دی",
    "url": "https://www.youtube.com/watch?v=-14zmcK-rEU&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=59&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 1803,
    "topic": "Administrative tasks"
  },
  {
    "index": 60,
    "title": "الپیک ۱ - ۰۶۰ - ماجول ۱۰۷.۳ - محلی‌سازی و جهانی‌سازی در لینوکس / تغییر تایم‌زون، تنظیمات منطقه‌ای",
    "url": "https://www.youtube.com/watch?v=BsNHQ95BbcA&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=60&pp=iAQB",
    "durationSeconds": 1017,
    "topic": "Administrative tasks"
  },
  {
    "index": 61,
    "title": "الپیک ۱ - ۰۶۱ - ماجول ۱۰۸.۱ - ۱/۲ - مدیریت زمان سیستم، درک زمان سخت‌افزاری و نرم‌افزاری و تایم‌زونها",
    "url": "https://www.youtube.com/watch?v=GN54NlA4wC4&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=61&pp=iAQB",
    "durationSeconds": 814,
    "topic": "Essential system services"
  },
  {
    "index": 62,
    "title": "الپیک ۱ - ۰۶۲ - ماجول ۱۰۸.۱ - ۲/۲ - مدیریت زمان سیستم، سرویس‌های تنظیم زمان بر اساس NTP",
    "url": "https://www.youtube.com/watch?v=Ihm6AYNFUKA&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=62&pp=iAQB",
    "durationSeconds": 975,
    "topic": "Essential system services"
  },
  {
    "index": 63,
    "title": "الپیک ۱ - ۰۶۳ - ماجول ۱۰۸.۲ - ۱/۳ - لاگ‌های سیستم، مفاهیم، کرنل رینگ بافر، دستور dmesg و logrotate",
    "url": "https://www.youtube.com/watch?v=vBDgTA-VYXo&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=63&pp=iAQB",
    "durationSeconds": 1456,
    "topic": "Essential system services"
  },
  {
    "index": 64,
    "title": "الپیک ۱ - ۰۶۴ - ماجول ۱۰۸.۲ - ۲/۳ - لاگ‌های سیستم، تنظیم و استفاده از rsyslog برای مدیریت لاگ‌ها",
    "url": "https://www.youtube.com/watch?v=T-ut4oQfJI8&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=64&pp=iAQB",
    "durationSeconds": 736,
    "topic": "Essential system services"
  },
  {
    "index": 65,
    "title": "الپیک ۱ - ۰۶۵ - ماجول ۱۰۸.۲ - ۳/۳ - لاگ‌های سیستم، بررسی و مدیریت لاگ‌ها با journalctl از systemd",
    "url": "https://www.youtube.com/watch?v=1_wf9O9QHCA&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=65&pp=iAQB",
    "durationSeconds": 1406,
    "topic": "Essential system services"
  },
  {
    "index": 66,
    "title": "الپیک ۱ - ۶۷ - ماجول ۱۰۸.۴ - مدیریت پرینترها و سیستم چاپ در لینوکس از طریق سرویس CUPS و دیگر ابزارها",
    "url": "https://www.youtube.com/watch?v=TzH9TN11Oss&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=66&pp=iAQB",
    "durationSeconds": 1148,
    "topic": "Essential system services"
  },
  {
    "index": 67,
    "title": "الپیک ۱ - ۶۶ - ماجول ۱۰۸.۳ - مدیریت ایمیل‌ از طریق Mail Agent Transferها",
    "url": "https://www.youtube.com/watch?v=NGr7IvBXxKc&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=67&pp=iAQB",
    "durationSeconds": 1235,
    "topic": "Essential system services"
  },
  {
    "index": 68,
    "title": "الپیک ۱ - ماجول ۱۰۹.۱ - ۰۶۸ - ۱/۳ - مقدمات شبکه، آشنایی با TCP/IP و مفاهیم اولیه",
    "url": "https://www.youtube.com/watch?v=Eq2Atp_Zd-s&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=68&pp=iAQB",
    "durationSeconds": 998,
    "topic": "Networking fundamentals"
  },
  {
    "index": 69,
    "title": "الپیک ۱ - ماجول ۱۰۹.۱ - ۰۶۹ - ۲/۳ - مقدمات شبکه، ساب‌نت، سابنتینگ و تبدیل باینری به دسیمال و برعکس",
    "url": "https://www.youtube.com/watch?v=8ptEav8iedA&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=69&pp=iAQB",
    "durationSeconds": 866,
    "topic": "Networking fundamentals"
  },
  {
    "index": 70,
    "title": "الپیک ۱ - ماجول ۱۰۹.۱ - ۰۷۰ - ۳/۳ - مقدمات شبکه، پروتکل‌های ارتباطی، TCP, UDP, ICMP و پورتها و IPv6",
    "url": "https://www.youtube.com/watch?v=TnjgsERAL-o&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=70&pp=iAQB",
    "durationSeconds": 1005,
    "topic": "Networking fundamentals"
  },
  {
    "index": 71,
    "title": "الپیک ۱ - ۰۷۱ - ماجول ۱۰۹.۲ - ۱/۲ - تظیمات پایدار شبکه، مقدمات و دستورات و فایلهای تنظیمات شبکه",
    "url": "https://www.youtube.com/watch?v=LyKaGUR21iY&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=71&pp=iAQB",
    "durationSeconds": 1393,
    "topic": "Networking fundamentals"
  },
  {
    "index": 72,
    "title": "الپیک ۱ - ۰۷۲ - ماجول ۱۰۹.۲ - ۲/۲ - تظیمات پایدار شبکه، تنظیمات اسم هاست (هاست نیم)، دی ان اس و...",
    "url": "https://www.youtube.com/watch?v=bVH-K-zAY78&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=72&pp=iAQB",
    "durationSeconds": 850,
    "topic": "Networking fundamentals"
  },
  {
    "index": 73,
    "title": "الپیک ۱ - ۰۷۳ - ماجول ۱۰۹.۳ - ۱/۲ - عیب‌یابی مقدماتی شبکه. آی‌پی و مسیریابی و پینگ",
    "url": "https://www.youtube.com/watch?v=-OVEED6HcYA&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=73&pp=iAQB",
    "durationSeconds": 1381,
    "topic": "Networking fundamentals"
  },
  {
    "index": 74,
    "title": "Elpic 1 - 074 - Module 109.3 - 2/2 - Basic Network Troubleshooting. Checking, Establishing, and T...",
    "url": "https://www.youtube.com/watch?v=QNjP3B1kwdw&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=74&pp=iAQB",
    "durationSeconds": 907,
    "topic": "Networking fundamentals"
  },
  {
    "index": 75,
    "title": "الپیک ۱ - ۰۷۵ - ماجول ۱۰۹.۴ - سرویس دی ان اس در سمت کلاین",
    "url": "https://www.youtube.com/watch?v=DHRbLyPOxLw&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=75&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 905,
    "topic": "Networking fundamentals"
  },
  {
    "index": 76,
    "title": "الپیک ۱ - ۰۷۶ - ماجول ۱۱۰.۱ (۱/۲) - اقدامات مدیریتی مربوط به کاربران (سو، سودو، پسورد و محدودیت‌ها)",
    "url": "https://www.youtube.com/watch?v=ufZVe7eW_aw&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=76&pp=iAQB",
    "durationSeconds": 1676,
    "topic": "Security"
  },
  {
    "index": 77,
    "title": "Elpic 1 - 077 - Module 110.1 (2/2) - User-related administrative actions; checking open ports and...",
    "url": "https://www.youtube.com/watch?v=mumlrHpLheY&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=77&pp=iAQB0gcJCaMLAYcqIYzv",
    "durationSeconds": 911,
    "topic": "Security"
  },
  {
    "index": 78,
    "title": "الپیک ۱ - ۰۷۸ - ماجول ۱۱۰.۲ - اقدامات امنیتی مربوط به هاست؛ مدیریت ورود، سوپر سرورها و مدیریت سرویس",
    "url": "https://www.youtube.com/watch?v=6FNkpn3q3F8&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=78&pp=iAQB",
    "durationSeconds": 1287,
    "topic": "Security"
  },
  {
    "index": 79,
    "title": "LPIC-1 - 079 - Module 110.3 (1/3) - Securing a system through encryption, the concept of key pair...",
    "url": "https://www.youtube.com/watch?v=qfARNLChgpE&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=79&pp=iAQB",
    "durationSeconds": 1234,
    "topic": "Security"
  },
  {
    "index": 80,
    "title": "الپیک ۱ - ۰۸۰ - ماجول ۱۱۰.۳ (۲/۳) - امن کردن سیستم از طریق رمزنگاری، درک خوب از تونل‌های اس اس اچ",
    "url": "https://www.youtube.com/watch?v=YYm3U8hnszo&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=80&pp=iAQB",
    "durationSeconds": 1288,
    "topic": "Security"
  },
  {
    "index": 81,
    "title": "الپیک ۱ - ۰۸۱ - ماجول ۱۱۰.۳ (۳/۳) - امن کردن سیستم از طریق رمزنگاری، رمزکردن اطلاعات با ابزار gpg",
    "url": "https://www.youtube.com/watch?v=BhF5pqdVxsA&list=PL-tKrPVkKKE0kM18Sg5fqaZW1V2nidAeU&index=81&pp=iAQB",
    "durationSeconds": 1332,
    "topic": "Security"
  }
];
